### PR TITLE
Soe 627

### PR DESCRIPTION
**Pull request by cjwest**
@boznik : I'm creating this PR so you can see what's up. I'll put it up on the soe-new-dev site and let you know when it's ready.

### CODE REVIEW

**Comment by cjwest** [comment]
Okay Mr. @boznik, she's ready for you!

Check out these:
the node:  https://sites.stanford.edu/jse-soe-new-dev/node/10350/edit
the imported items:  https://sites.stanford.edu/jse-soe-new-dev/news/recent-news

Lookin' forward to your comments or merge! Our designer, Kerri, is all ready to start making these look all purdy.

**Comment by boznik** [comment]
this isn't running on cron

**Comment by cjwest** [comment]
Hi @boznik , Do you happen to have suggestions on how to address the cron issue?

**Comment by boznik** [comment]
It is working.

**Comment by cjwest** [comment]
W00t!!!

**Pull request merged**
