### PR TITLE
D8CORE-2832: fix look of focus around news linked <h2>.

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary
Fixes how the look of the focus looks on <h2>

# Needed By (Date)
Soon

# Urgency
I believe https://github.com/SU-SWS/saa_victoria_subtheme/pull/139 would benefit.
I had been waiting for https://github.com/SU-SWS/decanter/pull/785, but there's really no need.

# Steps to Test

1. Check out this branch
2. Clear the cache
3. Verify the focus looks like:
Screen Shot 2021-02-04 at 1 14 27 PM

# Affected Projects or Products
- D8Core, SoE, SAA

# Associated Issues and/or People
- JIRA ticket: https://stanfordits.atlassian.net/browse/D8CORE-2832
- Other PRs
   https://github.com/SU-SWS/decanter/pull/785
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)
@ishahism 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by cjwest** [comment]
@katrialesser and @jenbreese,
I'm still working on the PR for the new focus style. However, this PR need not wait. 

Before:
Screen Shot 2021-02-04 at 1 13 40 PM

After:
Screen Shot 2021-02-04 at 1 14 27 PM

**Comment by jenbreese** [comment]
@cjwest Is this supposed to be for today?

**Comment by jenbreese** [comment]
@cjwest I pulled it in and it doesn't look like I think you want. The article "News is Great #2" acts really weird. 
Screen Shot 2021-02-04 at 3 32 27 PM
Screen Shot 2021-02-04 at 3 32 19 PM
Screen Shot 2021-02-04 at 3 32 10 PM

**Comment by cjwest** [comment]
@jenbreese,
Thank you  for finding these!

**Comment by cjwest** [comment]
@jenbreese 
Well, I'm stumped on this. My first thought would be to do something like:

 ```
 h2:focus
    {
      outline: 5px solid rebeccapurple;
    }
  a:focus
    {
      outline: none;
    }

```
and put a `tabindex="-1"` on the `<h2>` but that seems pretty janky. 😬 

I'm curious if you or @katrialesser have any ideas? @yvonnetangsu ?

**Comment by cjwest** [comment]
To make this work it appears that it'll take a bit of restructuring. Jen mentioned that Mike might be considering restructuring/refactoring news. If that's the case, we should roll this work into that. 
@pookmish, do you have anything to add?
@ishahism FYI

**Comment by pookmish** [comment]
@cjwest there is a ticket to convert the markup from `<ul>` and `<li>` elements to regular `<div>` elements. I'm not sure if that would change how you implement the focus styles on the header link. see https://stanfordits.atlassian.net/browse/D8CORE-2888

**Comment by cjwest** [comment]
> @cjwest there is a ticket to convert the markup from `<ul>` and `<li>` elements to regular `<div>` elements. I'm not sure if that would change how you implement the focus styles on the header link. see https://stanfordits.atlassian.net/browse/D8CORE-2888

@pookmish,
Ahh good to know!
To get the focus to not cut through the header link text, we'll need to refactor the CSS, or  completely re-think how we implement the focus area. If we're already making changes, let's include the focus!

@ishahism I think we might want to go back and define how the focus should look on the news item:

- One possibility is to make it behave more like a card and have some of the text wrapped in the focus area. 
- Another would be to just make the header the link and skip the image. 

I'm sure you might have other suggestions?

**Comment by jenbreese** [comment]
HI @cjwest Can we close this pull request? It reads like there is more dev to do.

**Comment by cjwest** [comment]
@jenbreese,
Yeah, there's more to think about here.

**Pull request closed without merging**
