### PR TITLE
HSDO-171 HSDO-728 Added masonry view

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Changed `news/recent-news` page to display using masonry.

# Needed By
- 3/1

# Urgency
- Requested by end of spring on 3/1

# Steps to Test
1. Checkout branch
2. Clear cache and revert stanford_news_views feature
3. If no news content is create, create some with pictures
4. View the page `news/recent-news` to validate the masonry view

# Associated Issues and/or People
- HSDO-728
- HSDO-659

### CODE REVIEW

**Comment by sherakama** [comment]
I pulled this down to an older JSA build and I get this:

screen shot 2017-02-28 at 1 33 58 pm

**Comment by sherakama** [comment]
What css is missing?

**Comment by sherakama** [comment]
Also, this is a pretty radical change to one of our very most used views. We should bring this change up with the other product owners. We might have to move this to it's own view, or at the very least, put this in to a 4.x version.

**Comment by sherakama** [comment]
The working example: https://sites.stanford.edu/demo-opportunities/masonry/recent-news

**Comment by pookmish** [comment]
I think that is the correct style. I don't believe any css is missing. I agree about possibly moving this to a 4.x version. Something we can bring up.

**Pull request closed without merging**
