### PR TITLE
Soe conflict warning

### PR DESCRIPTION
**Pull request by boznik**

### CODE REVIEW

**Comment by cjwest** [comment]
Very nice, @boznik !


screen shot 2016-05-26 at 12 26 06

**Comment by cjwest** [comment]
May want to see where errors are coming from:
https://stanfordits.atlassian.net/browse/SOE-796?focusedCommentId=44482&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-44482

**Comment by cjwest** [comment]
@boznik can we add 
1) check to see if the view is in the DB and then disabled and disable view
2) add a note to the log 
3) Maybe even a drupal_set_message to let the user know what happened.

 https://stanfordits.atlassian.net/browse/SOE-686?focusedCommentId=44731&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-44731

**Comment by boznik** [comment]
this was pulled into soe 811

**Pull request closed without merging**
