### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by sherakama**

### CODE REVIEW

**Comment by cjwest** [comment]
Hey @sherakama,

Sanity check here:

I would have expected this to be merged into `7.x-3.x-dev`. Yet, I see that you're merging into `7.x-3.x-jsvpsa`. Is that what you what?

**Comment by sherakama** [comment]
Good checking. There are two PRs. One for this branch and one for the 7.x-3.x branch. It needs to go in to both.

**Comment by cjwest** [comment]
You're not supposed to see this until morning. Go get a life!

**Comment by cjwest** [comment]
Looks good!

````
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing composer/installers (v1.5.0)
    Loading from cache

  - Installing su-sws/stanford_news (dev-composer 4fc0d31)
    Cloning 4fc0d317dbbeae4e582adccc12086f2653214de3 from cache

Writing lock file
Generating autoload files
cjwest:~/working$ more modules/custom/stanford_news/stanford_news.info
name = Stanford News JSVPSA
description = News Item content type, and list Views with an image and taxonomy terms
core = 7.x
package = Stanford
version = 7.x-3.2-jsvpsa
project = stanford_news
````

**Pull request merged**
