### PR TITLE
HSDO-687 HSDO-469 Created rss and xml importers

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Created rss importer for wordpress search string "http://news.stanford.edu/?feed=rss2&s=word"
Created XML importer for engineering import with upgrade for stanford_news_extras_importer

# Needed By (Date)
- 3/15

# Urgency
- not critical

# Steps to Test

1. Checkout the branch
2. enable stanford_news_importers module
3. run database updates
4. if desired, enable stanford_feeds_helper_multiple
5. create node "news Importer"
6. add the rss url and import.
7. if the xml feed is enabled and stanford_feeds_helper_multiple module is enabled add the xml to another node and import

### CODE REVIEW

**Comment by boznik** [comment]
@pookmish can you clear up the cc noise?

**Comment by boznik** [comment]
From the code it looks like i should also install stanford_news_extras_importer for testing.

**Comment by pookmish** [comment]
You could. From what Caryl said is the news_extras_importer is mostly abandoned. So it was mostly just an extra upgrade path to prevent sites from breaking.

**Comment by boznik** [comment]
gotcha, ok thx. will check.

**Pull request merged**
